name: Foundry Code Coverage

on: pull_request

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge version
        run: |
          forge --version
        id: version

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge Coverage
        run: |
          forge coverage --no-match-coverage "(script|test|wormhole/external/wormhole|wormhole/external/callworm/GettersGetter)" --report lcov
        id: test

      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: 'ga'

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.7
        with:
          reports: lcov.info
          targetdir: coveragereport
          reporttypes: MarkdownSummaryGithub

      - name: Add coverage summary to GitHub PR
        run: |
          cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

      - name: Read Markdown summary into variable
        id: coverage_summary
        run: |
          echo 'summary<<EOF' >> $GITHUB_OUTPUT
          cat coveragereport/SummaryGithub.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      
      - name: Post coverage comment to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.coverage_summary.outputs.summary }}